### ISSUE TITLE
UnsupportedOperationException => .setTraits((List<String>) device.get("traits"))

### ISSUE THREAD

**Issue by tranmanh90** [actions-on-google/smart-home-java#1]
public SyncResponse onSync(SyncRequest syncRequest, Map<?, ?> headers) {

        SyncResponse response = new SyncResponse();
        response.setRequestId(syncRequest.requestId);
        response.setPayload(new SyncResponse.Payload());
        response.payload.agentUserId = "1836.15267389";

        String userId = getUserId(headers);
        database.setHomegraph(userId, true);
        List<QueryDocumentSnapshot> devices = database.getDevices(userId);
        int numOfDevices = devices.size();
        response.payload.devices = new SyncResponse.Payload.Device[numOfDevices];
        for (int i = 0; i < numOfDevices; i++) {
            QueryDocumentSnapshot device = devices.get(i);
            SyncResponse.Payload.Device.Builder deviceBuilder =
                    new SyncResponse.Payload.Device.Builder()
                            .setId(device.getId())
                            .setType((String) device.get("type"))
                            **.setTraits((List<String>) device.get("traits"))**
                            .setName(DeviceProto.DeviceNames.newBuilder()
                                    .addAllDefaultNames((List<String>) device.get("defaultNames"))
                                    .setName((String) device.get("name"))
                                    .addAllNicknames((List<String>) device.get("nicknames"))
                                    .build())
                            .setWillReportState((Boolean) device.get("willReportState"))
                            .setRoomHint((String) device.get("roomHint"))
                            .setDeviceInfo(DeviceProto.DeviceInfo.newBuilder()
                                    .setManufacturer((String) device.get("manufacturer"))
                                    .setModel((String) device.get("model"))
                                    .setHwVersion((String) device.get("hwVersion"))
                                    .setSwVersion((String) device.get("swVersion"))
                                    .build());
            if (device.contains("attributes")) {
                Map<String, Object> attributes = new HashMap<>();
                attributes.putAll((Map<String, Object>) device.get("attributes"));
                JSONObject attributesJson = new JSONObject(attributes);
                Struct.Builder attributeBuilder = Struct.newBuilder();
                try {
                    JsonFormat.parser().ignoringUnknownFields()
                            .merge(attributesJson.toString(), attributeBuilder);
                } catch (Exception e) {
                    LOGGER.error("FAILED TO BUILD");
                }
                deviceBuilder.setAttributes(attributeBuilder.build());
            }
            if (device.contains("customData")) {
                Map<String, Object> customData = new HashMap<>();
                customData.putAll((Map<String, Object>) device.get("customData"));
                JSONObject customDataJson = new JSONObject(customData);
                deviceBuilder.setCustomData(customDataJson.toString());
            }
            response.payload.devices[i] = deviceBuilder.build();
        }

        return response;
    }

response = {"token_type":"bearer","access_token":"123access","expires_in":86400,"refresh_token":"123refresh"}
2019-06-06 16:59:48.872  INFO 10596 --- [p-nio-80-exec-3] com.example.MySmartHomeApp               : doPost, body = {"inputs":[{"intent":"action.devices.SYNC"}],"requestId":"12878346687558548143"}
java.lang.UnsupportedOperationException
	at com.google.protobuf.AbstractProtobufList.ensureIsMutable(AbstractProtobufList.java:177)
	at com.google.protobuf.LazyStringArrayList.clear(LazyStringArrayList.java:213)
	at com.google.actions.api.smarthome.SyncResponse$Payload$Device$Builder.setTraits(SmartHomeResponse.kt:125)
	at com.example.MySmartHomeApp.onSync(MySmartHomeApp.java:61)
	at com.google.actions.api.smarthome.SmartHomeApp.routeRequest(SmartHomeApp.kt:108)
	at com.google.actions.api.smarthome.SmartHomeApp.handleRequest(SmartHomeApp.kt:93)
	at com.example.SmartHomeServlet.doPost(SmartHomeServlet.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

Please help me fix it

**Comment by Fleker** [comment]
This might be because [in the library code](https://github.com/actions-on-google/actions-on-google-java/blob/master/src/main/kotlin/com/google/actions/api/smarthome/SmartHomeResponse.kt#L124) the list is being cleared and set without being fully instantiated? I'll look into it.

**Comment by Fleker** [comment]
I found the error. While this will be fixed in the next library release, you can get around it now by transforming the `setTraits` function to a series of `addTrait` calls.

**Comment by Fleker** [comment]
This [is fixed](https://github.com/actions-on-google/actions-on-google-java/commit/670d6a4ae2bd385de73b9cc068282cbed360047b) in version 1.2.0.
