### ISSUE TITLE
Failed to update device

### ISSUE THREAD

**Issue by murilobaliego** [actions-on-google/smart-home-java#10]
I'm getting this error now when trying to update a device.

2020-06-03 21:09:16.398 BRT
[i~smart-devices-mbfa/20200603t204127.427141936313333426].<stdout>: 2020-06-04 00:09:16 [Request873C78D0] INFO :: doPost, body = {"userId":"1234","deviceId":"1h6m","errorCode":"","states":{"on":false,"online":true},"tfa":""}

2020-06-03 21:09:17.059 BRT
[i~smart-devices-mbfa/20200603t204127.427141936313333426].<stdout>: 2020-06-04 00:09:16 [Request873C78D0] ERROR:: failed to update device: {}
java.lang.IllegalArgumentException: You must pass credentials in the app constructor
	at com.google.actions.api.smarthome.SmartHomeApp.reportState(SmartHomeApp.kt:124)
	at com.example.ReportState.makeRequest(ReportState.java:96)
	at com.example.SmartHomeUpdateServlet.doPost(SmartHomeUpdateServlet.java:86)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:757)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:720)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:690)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:882)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)

**Comment by murilobaliego** [comment]
I have an arduino code that works with realtime database in firebase, do you have any example of arduino code to work with this java backend that uses Cloud Firestore? Or any suggestions on how to implement the device client? I mean the requirements? For instance shoudl use gRPC or websockets or? I was using this Arduino Firebase API https://github.com/FirebaseExtended/firebase-arduino but as I said it uses realtime database
Thanks in advance.

**Comment by Fleker** [comment]
I don't know that Firestore works in an Arduino environment. You may need to modify the behavior of [MyDataStore](https://github.com/actions-on-google/smart-home-java/blob/master/src/main/java/com/example/MyDataStore.java) to use Firebase Realtime Database instead.

The update error happens when the [service account key](https://github.com/actions-on-google/smart-home-java#credentials) is not in the app constructor.

**Comment by murilobaliego** [comment]
Thanks @Fleker the update error was indeed caused by service account key, it was not missing, I created a new one and replace and then started working.

Regarding the Arduino or any other device, how it should interact with this back-end? I mean, what should be the best way to update values and receive the actions? By websocket or any other API? Sorry if those are too basic questions ;)

**Comment by Fleker** [comment]
I don't have enough familiarity with the Arduino platform and potential connectivity limitations to say what the best mechanisms are.

**Comment by murilobaliego** [comment]
Ok, still on this issue, when I send commands from mobile app, the request is handled correctly in end point /smarthome

However when I use the front end application, for instance clicking on switch botton, then end point /smarthome/update is reached and the error below still happening. Should front-end send anything related to credentials in post request?

    logMessage: "[i~smart-devices-mbfa/20200604t140043.427158679909140022].<stdout>: 2020-06-04 23:10:28 [RequestA6290CCD] ERROR:: failed to update device: {}
java.lang.IllegalArgumentException: You must pass credentials in the app constructor
	at com.google.actions.api.smarthome.SmartHomeApp.reportState(SmartHomeApp.kt:124)
	at com.example.ReportState.makeRequest(ReportState.java:96)
	at com.example.SmartHomeUpdateServlet.doPost(SmartHomeUpdateServlet.java:86)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)

![smartHome_update_error](https://user-images.githubusercontent.com/25311122/83820307-b8966c00-a6a2-11ea-962d-6e4d81ad6b02.png)

**Comment by Fleker** [comment]
Credentials should be passed in the [SmartHomeApp or your subclass](https://github.com/actions-on-google/actions-on-google-java/blob/master/src/main/kotlin/com/google/actions/api/smarthome/SmartHomeApp.kt#L28) credential on the server-side.

**Comment by murilobaliego** [comment]
it turns out that I had to add a **slash** in front of the credentials file name to make it work.

          GoogleCredentials.fromStream(getClass().getResourceAsStream("/smart-home-key.json"));
