### ISSUE TITLE
Exception on reportState

### ISSUE THREAD

**Issue by kangbudz** [actions-on-google/smart-home-java#4]
I have try this smart-home-java code sample along with smart-home-front end device sample [https://github.com/actions-on-google/smart-home-frontend](url) for simulating device. But exception still occurred in reportState and each device has different behaviour. 
Sample use case : 
- add 2 devices plug outlet and rgb light
- change states of outlet --> no exception occurred
- change states of rgb light --> **exception occured**

is this caused by homegraph API, frontend device simulator or action on google library Java ? Thanks

Below is sample of log out from both when exception occured in report state : 
**Smart Plug Change State** 
`2019-11-14 08:04:51 [qtp1204167249-13] INFO :: doPost, body = {"userId":"1234","deviceId":"130t","errorCode":"","states":{"on":false,"online":true}}
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] OUTBOUND HEADERS: streamId=9 headers=GrpcHttp2OutboundHeaders[:authority: firestore.googleapis.com:443, :path: /google.firestore.v1beta1.Firestore/Commit, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.25.0, x-goog-api-client: gl-java/1.8.0_222 gccl/0.61.0-beta gapic/0.61.0-beta gax/1.30.0 grpc/1.25.0, google-cloud-resource-prefix: projects/zetta-9f153/databases/(default), grpc-accept-encoding: gzip, authorization: Bearer ya29.c.KmewB1DFioTZbtfCUBOC_oDZmouh7kAcv0Jy9N2wr1Uhr6Fsw6hmUakpsSrbrhNvkocRxDtB0Jwe9gWVpthPyaJ2pMSqHB7XTOV_ufmYRdHMVOZQmKlLypNAN5T7fAEUK8sgiS-1cZlr] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] OUTBOUND DATA: streamId=9 padding=0 endStream=true length=180 bytes=00000000af0a2870726f6a656374732f7a657474612d39663135332f6461746162617365732f2864656661756c74291282010a720a4a70726f6a656374732f7a...
Send Report State
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] OUTBOUND HEADERS: streamId=11 headers=GrpcHttp2OutboundHeaders[:authority: firestore.googleapis.com:443, :path: /google.firestore.v1beta1.Firestore/Commit, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.25.0, x-goog-api-client: gl-java/1.8.0_222 gccl/0.61.0-beta gapic/0.61.0-beta gax/1.30.0 grpc/1.25.0, google-cloud-resource-prefix: projects/zetta-9f153/databases/(default), grpc-accept-encoding: gzip, authorization: Bearer ya29.c.KmewB1DFioTZbtfCUBOC_oDZmouh7kAcv0Jy9N2wr1Uhr6Fsw6hmUakpsSrbrhNvkocRxDtB0Jwe9gWVpthPyaJ2pMSqHB7XTOV_ufmYRdHMVOZQmKlLypNAN5T7fAEUK8sgiS-1cZlr] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] OUTBOUND DATA: streamId=11 padding=0 endStream=true length=162 bytes=000000009d0a2870726f6a656374732f7a657474612d39663135332f6461746162617365732f2864656661756c742912710a5e0a4a70726f6a656374732f7a65...
2019-11-14 08:04:51 [qtp1204167249-13] DEBUG:: devices {
  states {
    fields {
      key: "130t"
      value {
        struct_value {
          fields {
            key: "online"
            value {
              bool_value: true
            }
          }
          fields {
            key: "on"
            value {
              bool_value: false
            }
          }
        }
      }
    }
  }
}

2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] HANDSHAKEN: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=16384}
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] OUTBOUND SETTINGS: ack=true
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: homegraph.googleapis.com, :path: /google.home.graph.v1.HomeGraphApiService/ReportStateAndNotification, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.25.0, grpc-accept-encoding: gzip, authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU3ZWViNTE4ODFkZWRlOWZmNGQ5MmZmMGJiMWE1NjFiODJiMWM4MGQiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL2hvbWVncmFwaC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaG9tZS5ncmFwaC52MS5Ib21lR3JhcGhBcGlTZXJ2aWNlIiwiZXhwIjoxNTczNjk3MDkxLCJpYXQiOjE1NzM2OTM0OTEsImlzcyI6InpldHRhLTlmMTUzQGFwcHNwb3QuZ3NlcnZpY2VhY2NvdW50LmNvbSIsInN1YiI6InpldHRhLTlmMTUzQGFwcHNwb3QuZ3NlcnZpY2VhY2NvdW50LmNvbSJ9.J6bPn6gghmYBSTaYPq8xrYd-vfIMSn04SuRh9ad6T2r5cRYEeA1RE660sUrthGK9xISJLxxOBuHE5WS3xietFv7zCutQuWT8fUWp-jNQXzBIBJjDH079HLDuawCHJh7ulH_bkCbMI3nbQR1NUcd_aDmb8xECMr7vhG3ugxcOkJVXnPznGTN34wEbFkcTqilRoPMzNyTLJ1qRyqyaR_A5HiMzmRLrfySmejSlqVy9PDDdIvXZG3868n1V6V0oha3whCTqJiD3kjq4KGFOWTiRUPQnekb2QEme7MH62it1Z2OQk1xf_2GZp4-Toqn2NEQd2Q8lxYrrTZI5whcFlCWYRA] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=83 bytes=000000004e0a13302e3131303139313239393638393830343638120d313833362e31353236373338391a280a260a240a220a0431333074121a2a180a0c0a066f...
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] INBOUND SETTINGS: ack=true
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] INBOUND HEADERS: streamId=9 headers=GrpcHttp2ResponseHeaders[:status: 200, content-disposition: attachment, content-type: application/grpc, date: Thu, 14 Nov 2019 01:04:51 GMT, alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000] padding=0 endStream=false
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] INBOUND DATA: streamId=9 padding=0 endStream=false length=35 bytes=000000001e0a0e0a0c08b3d0b2ee0510c0f090fd01120c08b3d0b2ee0510c0f090fd01
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] INBOUND HEADERS: streamId=9 headers=GrpcHttp2ResponseHeaders[grpc-status: 0, content-disposition: attachment] padding=0 endStream=true
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] INBOUND PING: ack=false bytes=4
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] OUTBOUND PING: ack=true bytes=4
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-disposition: attachment, content-type: application/grpc, date: Thu, 14 Nov 2019 01:04:51 GMT, alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000] padding=0 endStream=false
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] INBOUND DATA: streamId=3 padding=0 endStream=false length=26 bytes=00000000150a13302e3131303139313239393638393830343638
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0, content-disposition: attachment] padding=0 endStream=true
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] INBOUND PING: ack=false bytes=0
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-1] DEBUG:: [id: 0x28d6dec8, L:/192.168.0.109:49216 - R:homegraph.googleapis.com/172.217.194.95:443] OUTBOUND PING: ack=true bytes=0
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] INBOUND HEADERS: streamId=11 headers=GrpcHttp2ResponseHeaders[:status: 200, content-disposition: attachment, content-type: application/grpc, date: Thu, 14 Nov 2019 01:04:51 GMT, alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000] padding=0 endStream=false
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] INBOUND DATA: streamId=11 padding=0 endStream=false length=35 bytes=000000001e0a0e0a0c08b3d0b2ee0510c0f090fd01120c08b3d0b2ee0510b8d1b4fe01
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] INBOUND HEADERS: streamId=11 headers=GrpcHttp2ResponseHeaders[grpc-status: 0, content-disposition: attachment] padding=0 endStream=true
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] INBOUND PING: ack=false bytes=6
2019-11-14 08:04:51 [grpc-default-worker-ELG-1-3] DEBUG:: [id: 0x9b37d3a1, L:/192.168.0.109:49208 - R:firestore.googleapis.com/172.217.194.95:443] OUTBOUND PING: ack=true bytes=6`

**RGB Light Change State** 

`2019-11-14 07:55:06 [qtp1204167249-17] INFO :: doPost, body = {"userId":"1234","deviceId":"1jf9","nickname":"desklamp"}
Send Report State
2019-11-14 07:55:06 [grpc-default-worker-ELG-1-2] DEBUG:: [id: 0x3c10c220, L:/192.168.0.109:39480 - R:firestore.googleapis.com/74.125.24.95:443] OUTBOUND HEADERS: streamId=11 headers=GrpcHttp2OutboundHeaders[:authority: firestore.googleapis.com:443, :path: /google.firestore.v1beta1.Firestore/Commit, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.25.0, x-goog-api-client: gl-java/1.8.0_222 gccl/0.61.0-beta gapic/0.61.0-beta gax/1.30.0 grpc/1.25.0, google-cloud-resource-prefix: projects/zetta-9f153/databases/(default), grpc-accept-encoding: gzip, authorization: Bearer ya29.c.KmewB1DFioTZbtfCUBOC_oDZmouh7kAcv0Jy9N2wr1Uhr6Fsw6hmUakpsSrbrhNvkocRxDtB0Jwe9gWVpthPyaJ2pMSqHB7XTOV_ufmYRdHMVOZQmKlLypNAN5T7fAEUK8sgiS-1cZlr] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2019-11-14 07:55:06 [qtp1204167249-17] DEBUG:: devices {
  **states {
    fields {
      key: "1jf9"
      value {
        struct_value {
        }
      }
    }
  }
}**

2019-11-14 07:55:06 [grpc-default-worker-ELG-1-2] DEBUG:: [id: 0x3c10c220, L:/192.168.0.109:39480 - R:firestore.googleapis.com/74.125.24.95:443] OUTBOUND DATA: streamId=11 padding=0 endStream=true length=168 bytes=00000000a30a2870726f6a656374732f7a657474612d39663135332f6461746162617365732f2864656661756c742912770a650a4a70726f6a656374732f7a65...
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] HANDSHAKEN: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=16384}
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] OUTBOUND SETTINGS: ack=true
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: homegraph.googleapis.com, :path: /google.home.graph.v1.HomeGraphApiService/ReportStateAndNotification, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.25.0, grpc-accept-encoding: gzip, authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU3ZWViNTE4ODFkZWRlOWZmNGQ5MmZmMGJiMWE1NjFiODJiMWM4MGQiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL2hvbWVncmFwaC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaG9tZS5ncmFwaC52MS5Ib21lR3JhcGhBcGlTZXJ2aWNlIiwiZXhwIjoxNTczNjk2NTA3LCJpYXQiOjE1NzM2OTI5MDcsImlzcyI6InpldHRhLTlmMTUzQGFwcHNwb3QuZ3NlcnZpY2VhY2NvdW50LmNvbSIsInN1YiI6InpldHRhLTlmMTUzQGFwcHNwb3QuZ3NlcnZpY2VhY2NvdW50LmNvbSJ9.Q-CFj9Sj8t4-1fyHQ3wx3w0CdCVm6koNsL7X0WK_kghLJakT2jHm6p9GMtPiHuRHmevPLv_amNIVN-tSgdWzjXEFMH_-rI1RaO10Co-uEEStVN0I5sHw9vQ_-ENEwHB1XrcLP4_wcDCJnadCkOL_-uxEJU6QwumpRpf9YKSbmnmbYmgDKtRDl0ZJLTy4d7rm0Q2Ir7WwhQqZS8eOoz7EGcdZN675tdtLDkx8so332jRKcvaJie_d8slMBh2TftbN8CP6vzLDiNl2cutqWR8iIoAA6hPK4gyCsskhJSgpLAXjYgI2rcjJqEMvU0DJ6VLqQWCYGYb0a9BTKl2nH5f31Q] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=59 bytes=00000000360a13302e3037343737393336323639323839353635120d313833362e31353236373338391a100a0e0a0c0a0a0a04316a663912022a00
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] INBOUND SETTINGS: ack=true
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, date: Thu, 14 Nov 2019 00:55:07 GMT, alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000] padding=0 endStream=false
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 3, grpc-message: Request contains an invalid argument.] padding=0 endStream=true
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] INBOUND PING: ack=false bytes=0
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] OUTBOUND PING: ack=true bytes=0
2019-11-14 07:55:07 [qtp1204167249-17] ERROR:: failed to update device
2019-11-14 07:55:07 [grpc-default-worker-ELG-1-8] DEBUG:: [id: 0x778fd1f6, L:/192.168.0.109:39500 - R:homegraph.googleapis.com/74.125.24.95:443] OUTBOUND RST_STREAM: streamId=3 errorCode=8
2019-11-14 07:55:07.351:WARN:oejs.HttpChannel:qtp1204167249-17: /smarthome/update
io.grpc.StatusRuntimeException: **INVALID_ARGUMENT: Request contains an invalid argument.**
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at com.google.home.graph.v1.HomeGraphApiServiceGrpc$HomeGraphApiServiceBlockingStub.reportStateAndNotification(HomeGraphApiServiceGrpc.java:519)
	at com.google.actions.api.smarthome.SmartHomeApp.reportState(SmartHomeApp.kt:132)
	at com.example.SmartHomeUpdateServlet.doPost(SmartHomeUpdateServlet.java:107)`

**Comment by Fleker** [comment]
This is probably due to a small discrepancy that may be present in the sample which requires some mitigation.

**Comment by kangbudz** [comment]
thank you @Fleker ...
right now i still checking why this issue happen... will update if got some clues..
